#!/bin/zsh
# Sass theme

prompt_sass_help () {
    cat <<'EOF'
Ayy it's a theme made by me. Try it out with:
    prompt sass
EOF
}

prompt_sass_setup () {
    PROMPT="%{$fg[cyan]%}[%n@%m] %{$fg[blue]%}%1~%{$reset_color%} %(!.#.$) "

    prompt_opts=(bang cr subst percent)
}

prompt_sass_setup "$@"
